/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  /**
   * EMITTED sample rate — the rate of the PCM handed to STT (16000 when the
   * resampler is active). Declare THIS to STT providers.
   */
  getSampleRate(): number
  /**
   * NATIVE hardware rate (e.g. 24000 for AirPods HFP, 48000 built-in) — for
   * diagnostics and HFP/Bluetooth-degradation detection only.
   */
  getNativeSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null, onSpeechEdge?: (((err: Error | null, arg: SpeechEdgeEvent) => any)) | undefined | null): void
  stop(): void
}

export declare class StealthKeyboardTap {
  constructor()
  /**
   * Engage the hook. Every plain-text keystroke fires `callback` and is
   * swallowed from the foreground app. `app_chords` is the app's OWN global
   * shortcuts (printable-leak subset) the hook should swallow + self-dispatch
   * so they can never leak into the foreground app while a `RegisterHotKey`
   * registration is temporarily dropped; pass `[]` to disable that (fully
   * inert — every chord passes through as before). `overlay_bounds` is
   * accepted for cross-platform parity and ignored (no outside-click stop on
   * Windows, matching the shipped macOS build). Idempotent while active.
   */
  start(callback: ((err: Error | null, arg: CapturedKey) => any), appChords: Array<AppChordInput>, shortcutOnly: boolean, overlayBounds?: OverlayBoundsInput | undefined | null): boolean
  /** No-op on Windows (accepted for API parity — see `start`). */
  updateOverlayBounds(overlayBounds?: OverlayBoundsInput | undefined | null): void
  /**
   * Disengage the hook. Safe to call when inactive. After this returns the
   * next keystroke reaches the foreground app normally.
   */
  stop(): void
  get isActive(): boolean
}

export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  /**
   * EMITTED sample rate — the rate of the PCM handed to STT (16000 when the
   * resampler is active). This is what callers must declare to STT providers.
   */
  getSampleRate(): number
  /**
   * NATIVE hardware sample rate (e.g. 48000) — for diagnostics and
   * HFP/Bluetooth-degradation detection only. NOT the rate of emitted bytes.
   */
  getNativeSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null, onSpeechEdge?: (((err: Error | null, arg: SpeechEdgeEvent) => any)) | undefined | null): void
  stop(): void
}

/**
 * napi input mirror of `AppChord`, passed from JS into `start()`. Defined here
 * (unconditionally compiled) so BOTH the macOS `keyboard_tap` and the Windows
 * `keyboard_hook_windows` modules — which each expose the identical
 * `StealthKeyboardTap.start` surface — can reference one napi object with a
 * single generated TS type. `vk`/`mods` come from
 * `electron/services/winChord.ts` (which owns the accelerator→VK translation).
 */
export interface AppChordInput {
  vk: number
  mods: number
  id: string
}

export interface AudioDeviceInfo {
  id: string
  name: string
}

/** Event payload delivered to the JS callback. Flat, matching macOS. */
export interface CapturedKey {
  /**
   * macOS HID virtual keycode (53=Esc, 36=Return, 76=NumpadEnter,
   * 51=Backspace). Translated from the Windows VK so the renderer's
   * hardcoded switch works unchanged. 0 for ordinary printable keys.
   */
  keyCode: number
  /**
   * The character(s) this key produces under the active layout + modifiers
   * (via ToUnicodeEx). Empty for non-printable keys.
   */
  chars: string
  /**
   * Modifier bitmask using the SAME bit layout the macOS tap emits
   * (cmd=1<<20, opt=1<<19, ctrl=1<<18, shift=1<<17, capsLock=1<<16) so the
   * renderer can decode identically. We only ever set shift/caps here
   * because modifier combos are passed through (see the filter below).
   */
  flags: number
  /** True for keyDown, false for keyUp. The renderer only acts on keyDown. */
  isKeyDown: boolean
  /**
   * True when the user has left Natively and stealth must stop: a click on
   * another process's window (mouse hook) or a foreground switch such as
   * Alt+Tab (WinEvent hook). StealthKeyboardManager turns this into stop().
   * Named for the macOS field it mirrors; on Windows it covers both triggers.
   */
  isOutsideMouseDown: boolean
  /**
   * Non-empty ⟹ this event is the app's OWN global shortcut firing, swallowed
   * by the hook so it can never leak into the foreground app. The value is
   * the KeybindManager action id; StealthKeyboardManager dispatches it
   * instead of treating the event as typed text. Empty for ordinary keys.
   */
  appChordId: string
}

/**
 * Deactivates a Dodo Payments license activation instance.
 *
 * `instance_id` — the activation instance ID (e.g. "lki_xxx") returned at activation time.
 * This is stored in the encrypted license file and passed here to free the slot.
 *
 * Returns a Promise resolving to "OK" or "ERR:dodo:<reason>".
 * Network errors return "ERR:dodo:network:..." — callers should still remove the local license
 * file even on network failure (fail-safe: local removal always happens).
 */
export declare function deactivateDodoKey(licenseKey: string, instanceId: string): Promise<unknown>

/**
 * Returns the platform-native ID of the current default output device.
 * macOS: CoreAudio device UID. Windows: WASAPI device id (eMultimedia/eConsole role).
 * Empty string on error or unsupported platform.
 *
 * JS polls this every few seconds during an active meeting; when the value
 * changes, main.ts recreates SystemAudioCapture so the CoreAudio Tap follows
 * the new output route. Without this, switching output devices mid-meeting
 * (plug in headphones, swap AirPods, route to virtual cable) leaves the tap
 * bound to the original device, capturing silence.
 */
export declare function getDefaultOutputDeviceId(): string

/**
 * Returns a deterministic hardware fingerprint (SHA-256 hash of the machine UID).
 * This is used to lock license keys to a specific physical device.
 */
export declare function getHardwareId(): string

export declare function getInputDevices(): Array<AudioDeviceInfo>

export declare function getOutputDevices(): Array<AudioDeviceInfo>

/**
 * One-shot poll of both states. Cheap enough to call every few seconds from
 * JS (electron/services/RemoteSessionGuard.ts); no allocation, no handle.
 */
export declare function getRemoteSessionState(): RemoteSessionState

/**
 * Windows needs no OS permission for a WH_KEYBOARD_LL hook (unlike macOS
 * Accessibility). Always true so the JS permission flow no-ops.
 */
export declare function isAccessibilityGranted(): boolean

/**
 * True when the active keyboard layout is a CJK IME (Chinese / Japanese /
 * Korean), i.e. one where text is composed rather than typed key-for-key.
 *
 * # Why the stealth hook is unusable for these users
 *
 * IME composition happens ABOVE the raw keyboard layer, in IMM32/TSF. Our
 * WH_KEYBOARD_LL hook swallows the keystroke (returns 1) before it ever
 * reaches that layer, and the text we substitute comes from `ToUnicodeEx`,
 * which resolves the layout but performs no composition. So with an IME
 * active, engaging the hook means the candidate window never appears and the
 * user can only enter raw Latin letters.
 *
 * macOS has exactly this problem with its CGEventTap and solves it by probing
 * the enabled input sources and declining to auto-engage (see
 * electron/services/ImeDetector.ts). This is the Windows probe for the same
 * decision. JS uses it to report stealth typing unavailable, which routes
 * these users through the existing no-hook fallback: the overlay stays a
 * normal focusable window and typing works through real DOM focus, at the cost
 * of the click stealing foreground focus. Composition that works beats silent,
 * unexplained mojibake.
 *
 * Reads the layout of the FOREGROUND thread (the app the user is actually
 * typing in), falling back to this process's layout when that is unavailable.
 */
export declare function isImeKeyboardActive(): boolean

/**
 * Overlay bounds accepted for API parity with macOS. Windows does not wire an
 * outside-click stop (neither does the shipped macOS build — its bounds
 * provider is never registered), so these are accepted and ignored.
 */
export interface OverlayBoundsInput {
  x: number
  y: number
  width: number
  height: number
}

export interface RemoteSessionState {
  /** True when this session is itself a Remote Desktop (RDP) connection. */
  isRemoteSession: boolean
  /**
   * True when this session is currently being shadowed/remote-controlled
   * by another session (`mstsc /shadow`), independent of whether the
   * session itself is console or RDP.
   */
  isRemoteControlled: boolean
}

/**
 * One joint-state transition from the dual-channel tracker
 * (`channel_state.rs`), delivered to JS through the optional third `start()`
 * callback of both captures. `atMs` is epoch ms (Date.now() timeline).
 */
export interface SpeechEdgeEvent {
  /** "interviewer" | "user" */
  channel: string
  speaking: boolean
  /** "neither" | "interviewer_speaking" | "user_speaking" | "both" */
  joint: string
  atMs: number
  /** ms since the OTHER channel's last edge; -1 when it has none yet. */
  msSinceOtherEdge: number
  /** false on Windows (mic is RMS-only, PR #497): user edges are weak evidence. */
  userEdgesVadBacked: boolean
}

/**
 * Validates an existing Dodo Payments license key against the live API.
 *
 * Used for periodic startup checks to detect server-side revocations.
 * Returns a Promise resolving to "OK", "REVOKED", or "ERR:dodo:...".
 * Network errors return "ERR:dodo:network:..." so callers can fail-open.
 */
export declare function validateDodoKey(licenseKey: string): Promise<unknown>

/**
 * Activates a Dodo Payments license key against the live API.
 *
 * `device_label` — first 32 chars of the HWID hash; passed as the `name` field so the
 * merchant can correlate activations to devices in the Dodo dashboard.
 *
 * Returns a Promise resolving to "OK:<instance_id>" on success, or "ERR:dodo:<reason>".
 * The HTTP call runs on a libuv worker thread to prevent blocking the Node.js event loop.
 */
export declare function verifyDodoKey(licenseKey: string, deviceLabel: string): Promise<unknown>

/**
 * Validates a Gumroad license key by calling the Gumroad Licenses API.
 * Returns a Promise that resolves to "OK" on success, or an error message string on failure.
 * The HTTP call runs on a libuv worker thread to prevent blocking the Node.js event loop.
 */
export declare function verifyGumroadKey(licenseKey: string): Promise<unknown>
